name: Docs

on:
  release:
    types:
      - created

jobs:
  generate:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Jazzy
        run: sudo gem instal jazzy

      - name: Generate Docs
        run: jazzy

      - uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: docs


